# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
  encoders:
    AppBundle\Entity\User:
      algorithm: bcrypt
    Symfony\Component\Security\Core\User\User: plaintext
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
      in_memory:
          memory:
            users:
              admin:
                password: adminpass
                roles: 'ROLE_ADMIN'
      our_db_provider:
        entity:
          class: AppBundle:User
          property: username

  firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
    admin:
        pattern: ^/admin
        http_basic:
          realm: 'Zone Administrateur'
          provider: in_memory
    main:
        http_basic: ~
        provider: our_db_provider
        anonymous: ~
        form_login:
          login_path: login
          check_path: login
        logout:
          path:   /logout
          target: /
        # activate different ways to authenticate

        # http_basic: ~
        # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

        # form_login: ~
        # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/back-office, roles: ROLE_USER }
    - { path: ^/draft, roles: ROLE_USER }
